import type { Metadata } from "next";
import { Mona_Sans, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Health Notion",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/default.png",
    apple: "/apple-touch-icon.png",
    shortcut: "/logo/default.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${monaSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
